const $=id=>document.getElementById(id); const api=()=>$('api').value.replace(/\/$/,'');
function msg(x){$('msg').textContent=x; setTimeout(()=>$('msg').textContent='',5000)}
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden'); if(id==='signals')loadSignals(); if(id==='dash'&&!window.gmChartLoaded)loadTVChart('XAUUSD')}
function sendContact(){const n=$('contactName').value.trim(),e=$('contactEmail').value.trim(),s=$('contactSubject').value.trim(),m=$('contactMessage').value.trim();if(!n||!e||!m){$('contactStatus').textContent='Please enter your name, email and message.';return} $('contactStatus').textContent='Message prepared. Please connect the contact form to your support email/API in the backend to deliver it.';msg('Contact message ready.')}
async function req(path,opt={}){let r=await fetch(api()+path,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j}
async function health(){try{let j=await req('/api/health');msg('API online: '+j.time);loadSymbols()}catch(e){msg(e.message)}}
async function loadSymbols(){try{let j=await req('/api/market/symbols');$('symbols').innerHTML=j.symbols.map(s=>`<button onclick="quote('${s}')">${s}</button>`).join(' ');$('marketStatus').textContent='Provider: '+j.provider}catch(e){$('symbols').textContent=e.message}}
const tvMap={XAUUSD:'OANDA:XAUUSD',XAGUSD:'OANDA:XAGUSD',EURUSD:'OANDA:EURUSD',GBPUSD:'OANDA:GBPUSD',USDJPY:'OANDA:USDJPY',USDCHF:'OANDA:USDCHF',USDCAD:'OANDA:USDCAD',AUDUSD:'OANDA:AUDUSD',NZDUSD:'OANDA:NZDUSD',EURJPY:'OANDA:EURJPY',GBPJPY:'OANDA:GBPJPY',BTCUSD:'BITSTAMP:BTCUSD',ETHUSD:'BITSTAMP:ETHUSD',NAS100:'OANDA:NAS100USD',US30:'OANDA:US30USD'};
function loadTVChart(s){$('chartTitle').textContent='Live Chart — '+s; $('tvChart').innerHTML=''; window.gmChartLoaded=true; if(window.TradingView){new TradingView.widget({autosize:true,symbol:tvMap[s]||s,interval:'5',timezone:'Etc/UTC',theme:'dark',style:'1',locale:'en',toolbar_bg:'#f1f3f6',enable_publishing:false,allow_symbol_change:true,container_id:'tvChart'});} else {$('tvChart').textContent='Chart library loading…';}}
async function quote(s){loadTVChart(s);try{let j=await req('/api/market/quote/'+s);let q=j.quote;$('quoteBox').innerHTML='<b>'+j.symbol+'</b><br>Price: '+(q.close??'—')+'<br>Open: '+(q.open??'—')+'<br>High: '+(q.high??'—')+'<br>Low: '+(q.low??'—')+'<br>Change: '+(q.percent_change??'—')+'%<br>Time: '+(q.datetime??'—');$('marketStatus').textContent='Live provider: '+j.provider}catch(e){$('quoteBox').textContent=e.message;msg(e.message)}}
async function loadCalendar(country){try{let j=await req('/api/calendar?country='+encodeURIComponent(country));let ev=j.events||[];$('calendarList').innerHTML=ev.length?'<table><tr><th>Date</th><th>Country</th><th>Event</th><th>Importance</th><th>Actual</th><th>Forecast</th><th>Previous</th></tr>'+ev.map(x=>'<tr><td>'+((x.Date||x.date||'').toString().replace('T',' ').slice(0,19))+'</td><td>'+(x.Country||x.country||'')+'</td><td>'+(x.Event||x.event||'')+'</td><td>'+(x.Importance||x.importance||'')+'</td><td>'+(x.Actual??x.actual??'')+'</td><td>'+(x.Forecast??x.forecast??'')+'</td><td>'+(x.Previous??x.previous??'')+'</td></tr>').join('')+'</table>':'No events returned.';}catch(e){$('calendarList').textContent=e.message;msg(e.message)}}
async function register(){try{let body={full_name:$('name').value,email:$('email').value,username:$('username').value,phone:$('phone').value,mt5_account:$('mt5').value,password:$('password').value};let j=await req('/api/register',{method:'POST',body:JSON.stringify(body)});msg(j.message)}catch(e){msg(e.message)}}
async function verifyOtp(){try{let j=await req('/api/verify-email',{method:'POST',body:JSON.stringify({email:$('email').value,code:$('otp').value})});msg('Email verified. Status: '+j.status)}catch(e){msg(e.message)}}
async function login(){try{let j=await req('/api/login',{method:'POST',body:JSON.stringify({username_or_email:$('loginId').value,password:$('loginPw').value})});$('loginOut').textContent=JSON.stringify(j.user,null,2);let b=$('licenseBox');b.classList.remove('hidden');b.innerHTML='<b>EA License Key</b><br>Paste this into the EA\'s <code>LicenseKey</code> input, with MT5 account <code>'+j.user.mt5_account+'</code> in <code>MT5AccountForLicense</code>:<br><code>'+j.user.license_key+'</code>';msg('Login successful')}catch(e){msg(e.message)}}
async function setMembership(){try{let body={email:$('memEmail').value,membership:$('memTier').value,membership_expiry:$('memExpiry').value||null};let j=await req('/api/admin/membership',{method:'POST',headers:{'X-Admin-Key':$('adminKey').value},body:JSON.stringify(body)});$('memStatus').textContent='Saved: '+j.membership+(j.membership_expiry?(' until '+j.membership_expiry):'');msg('Membership updated')}catch(e){$('memStatus').textContent=e.message;msg(e.message)}}
async function payment(kind){try{let amount=kind==='DEPOSIT'?$('depAmount').value:$('withAmount').value;let body={email:$('payEmail').value,kind,amount,currency:'USD',method:$('depMethod').value,reference:$('depRef').value,destination:$('withDest').value};let j=await req('/api/payment-request',{method:'POST',body:JSON.stringify(body)});msg(kind+' request: '+j.status)}catch(e){msg(e.message)}}
async function loadSignals(){try{let j=await req('/api/signals');$('signalList').innerHTML=j.signals.length?`<table><tr><th>Symbol</th><th>Direction</th><th>Entry</th><th>SL</th><th>TP1</th><th>Confidence</th></tr>${j.signals.map(x=>`<tr><td>${x.symbol}</td><td>${x.direction}</td><td>${x.entry??''}</td><td>${x.sl??''}</td><td>${x.tp1??''}</td><td>${x.confidence??''}</td></tr>`).join('')}</table>`:'No active signals yet.'}catch(e){msg(e.message)}}
async function loadAdmin(){let key=$('adminKey').value;try{let [u,p]=await Promise.all([req('/api/admin/users',{headers:{'X-Admin-Key':key}}),req('/api/admin/payments',{headers:{'X-Admin-Key':key}})]);$('adminUsers').innerHTML='<h3>Users</h3><pre>'+JSON.stringify(u.users,null,2)+'</pre>';$('adminPayments').innerHTML='<h3>Payments</h3><pre>'+JSON.stringify(p.payments,null,2)+'</pre>'}catch(e){msg(e.message)}}
loadSymbols(); setTimeout(()=>loadTVChart('XAUUSD'),300);
